### ISSUE TITLE
Benchmark with different convolutional layers blocks

### ISSUE THREAD

**Issue by AlexandreBriot** [davheld/GOTURN#15]
Hello, 
I've just read your paper and your network sounds very attractive in terms of inference speed.
I was wondering whether you benchmarked your solution with other architecture for your convolutional layers such as Squeezenet, Res-Net or GoogleNet ? Why did you chose to use CaffeNet as feature extractor ? 
Thanks in advance for your answer.

**Comment by davheld** [comment]
Hi - I did not test any other architectures.  I chose CaffeNet because:
1) It is fast
2) I have an intuitive sense, from other studies, that the pool5 layer of CaffeNet should contain most of the information that we need for tracking, whereas I don't have the same intuition for other network architectures
3) My contribution in the paper is orthogonal to the type of network used; you can feel free to experiment with other network architectures.

Best of luck!

**Comment by AlexandreBriot** [comment]
Thank you David for your answer.
And congratulations for your paper.
