### ISSUE TITLE
Any tricks about how to deal with occlusion?

### ISSUE THREAD

**Issue by brb-chen** [davheld/GOTURN#31]
As in the outdoor, the situation becomes complicated, e.g many vehicles, pedestrians, trunks ...

   i didn't see any specific idea about it in the paper, which i care much.

**Comment by davheld** [comment]
This is an open research question - not sure about the best way to deal with this.  I agree that it's an important problem.

One simple possibility is to use the first frame (frame 1) as the target frame, rather than the previous frame (frame t-1).  This would allow the network to "remember" better which object it is tracking, even despite occlusions.

**Comment by ujsyehao** [comment]
@brb-chen  you can watch C-COT tracker, it can deal with occlusion.
